[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/dashboard"
to = "https://tarry-omniscient-axolotl.glitch.me/api/coin"
status = 200
force = true
headers = {X-From = "Netlify"}